FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["bge-core\\src\\App.bf", "bge-core\\src\\Maths.bf", "bge-test\\src\\Test.bf", "d:\\a\\_work\\1\\s\\src\\vctools\\crt\\vcstartup\\src\\startup\\exe_common.inl"]

[MainWindow]
X = 1179
Y = 117
Width = 1577
Height = 1183
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 200.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.0968
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Maths.bf"
TabWidth = 87.90323
Type = "SourceViewPanel"
FilePath = "bge-core\\src\\Maths.bf"
CursorPos = 1763
ProjectName = "bge-core"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "exe_common.inl"
TabWidth = 129.8387
Type = "SourceViewPanel"
FilePath = "d:\\a\\_work\\1\\s\\src\\vctools\\crt\\vcstartup\\src\\startup\\exe_common.inl"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Test.bf"
TabWidth = 75.0
Type = "SourceViewPanel"
FilePath = "bge-test\\src\\Test.bf"
CursorPos = 175
ProjectName = "bge-test"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "App.bf"
TabWidth = 75.80645
Type = "SourceViewPanel"
FilePath = "bge-core\\src\\App.bf"
CursorPos = 51
ProjectName = "bge-core"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 65.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 3438.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Diagnostics"
TabWidth = 114.5161
Type = "DiagnosticsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 97.58064
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.48387
Type = "WatchPanel"
Columns = [{Width = 248.0}, {Width = 248.0}, {Width = 248.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 76.6129
Type = "AutoWatchPanel"
Columns = [{Width = 248.0}, {Width = 248.0}, {Width = 248.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 3438.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 94.35484
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.0323
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.6774
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 89.51613
Type = "OutputPanel"

[[Breakpoints]]
File = "bge-test\\src\\Test.bf"
Line = 10
Column = 0

[[Breakpoints]]
File = "bge-test\\src\\Test.bf"
Line = 11
Column = 0

[[Breakpoints]]
File = "bge-test\\src\\Test.bf"
Line = 12
Column = 0

[[Breakpoints]]
File = "bge-test\\src\\Test.bf"
Line = 13
Column = 0

[[BookmarkFolders]]
Title = ""
